<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NLayers.BusinessLogic\NLayers.BusinessLogic.csproj" />
    <ProjectReference Include="..\NLayers.Entities\NLayers.Entities.csproj" />
    <ProjectReference Include="..\..\core\NLayers.Core\NLayers.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
